# The baseUrl for the Solr server. If using Solr 4.x or better, the URL should include
# the core name.
solr.baseUrl=localhost:8983/solr/box

# The timeframe (in milliseconds) within which new items should be committed to the solr index.
solr.commitWithin=10000

# In the event of failure, the maximum number of times a redelivery will be attempted.
error.maxRedeliveries=2